[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]

gas_reports = ["*"]

remappings = ["@openzeppelin/contracts/=/root/ContractSafetyStudy/ethernaut/lib/openzeppelin-contracts/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
